### ISSUE TITLE
"Cannot find Fable.Compiler package" error in Fable examples

### ISSUE THREAD

**Issue by object** [fable-compiler/Fable#922]
### Description

I am just starting with Fable, fetched latest sources yesterday and now would like to play with its examples. After running build.cmd in Fable root directory I switch to example folders and examples build OK. However when I try to run a command

dotnet fable webpack-dev-server

I get an error:

ERROR: Cannot find Fable.Compiler package. Please make sure it's been added to `paket.dependencies`.

### Repro code

Here's a output from an attempt to build and run d3map project:

C:\Projects\Fable\samples\browser\d3map>dotnet restore
  Restoring packages for C:\Projects\Fable\samples\browser\d3map\d3map.fsproj...
  Restoring packages for C:\Projects\Fable\samples\browser\d3map\d3map.fsproj...
  Installing dotnet-fable 1.0.0.
  Restore completed in 5.25 sec for C:\Projects\Fable\samples\browser\d3map\d3map.fsproj.
  Installing Fable.Core 1.0.0-narumi-921.
  Writing lock file to disk. Path: C:\Projects\Fable\samples\browser\d3map\obj\project.assets.json
  Restore completed in 20.47 sec for C:\Projects\Fable\samples\browser\d3map\d3map.fsproj.

  NuGet Config files used:
      C:\Projects\Fable\NuGet.Config
      C:\Users\Vagif Abilov\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json

  Installed:
      2 package(s) to C:\Projects\Fable\samples\browser\d3map\d3map.fsproj

C:\Projects\Fable\samples\browser\d3map>dotnet fable webpack-dev-server
ERROR: Cannot find Fable.Compiler package. Please make sure it's been added to `paket.dependencies`.

### Related information 

I tried it on Windows 10 machine with Visual Studio 2017 and latest Visual F# Tools.

**Comment by Zaid-Ajaj** [comment]
@object Hello there, the samples are being updated at the moment. Each sample corrently in samples/browser is self-contained and should be built using the instructions in the respective README.md on each sample. You can see in #881 which samples are updated to latest Fable (v1.0 beta). 

Because we just had a major update yesterday regarding dependency management (moving to Paket!) the updated samples could also need to be updated to use Paket too. So it is expected if some of them break these couple of days until @fable-compiler/documentation re-update them again to use Paket

**Comment by object** [comment]
Thank you for a quick reply. Then I assume this is an issue related to the major upgrade. I will retry once update is complete and if issue is no longer present I will close it.

**Comment by alfonsogarciacaro** [comment]
Hi @object! (Nice GH alias btw!)

Yes, sorry, we had some issues with the Paket integration these last two days. Hopefully all the major ones should be fixed now (crossing fingers). We still need to check the samples, but at least the templates have been updated and are working, could you please give them a try?

```shell
# Install template, only first time (quote the last arg if necessary)
dotnet new -i Fable.Template::*

# Create a project 
dotnet new fable -n MySimpleCanvasApp

# Follow the instructions in the README
cd MySimpleCanvasApp
yarn install
dotnet restore
dotnet fable npm-run start
``` 

For the Elmish template just replace the first two steps with:

```shell
dotnet new -i Fable.Template.Elmish.React::*
dotnet new fable-elmish-react MyElmishApp
```

**Comment by object** [comment]
Hi @alfonsogarciacaro. I just updated and rebuilt source by doing the following:
1. Executed build.cmd in the root folder (everything OK)
2. Executed npm install in Samples folder as specified in README.MD for sample projects
3. Executed dotnet restore in the actual sample folders (e.g. pong or d3map)
4. Ran dotnet fable webpack-devserver

Still the same error:
ERROR: Cannot find Fable.Compiler package. Please make sure it's been added to paket.dependencies.

Isn't this happening on your machine? Or did I miss some extra step?

**Comment by MangelMaxime** [comment]
@object The samples are not fixed yet. So this is normal at the moment if you can't build them.
However both templates pointed by Alfonso are working.

Eugene told in the gitter this:

> for those getting the error telling you to install "Fable.Compiler", what you really need is to update the .fsproj to reference latest version of fable:
<DotNetCliToolReference Include="dotnet-fable" Version="1.0.4" />

**Comment by object** [comment]
Thanks, I will try to fix it myself.

**Comment by Zaid-Ajaj** [comment]
@object you can find the samples updated [in here](https://github.com/fable-compiler/samples)

**Comment by object** [comment]
Thanks. I will check them out and file an issue in case of problems.
