### ISSUE TITLE
Logo for Fable and Fable related projects

### ISSUE THREAD

**Issue by sergey-tihon** [fable-compiler/Fable#969]
We (together with my fiancee) thought how Fable logo may look like... with ideas to incorporate

- the concept that `Fable = F# |> Babel`
- show it in yellow color (js color)
- make it customizable (like `fsprojects` logo  template) to provide a template for projects like `fable-react` and others
- show appreciation to @alfonsogarciacaro with a sign that project was born in Spain. 

That's what we got and we would love to hear the feedbacks:
![fullsizeoutput_7f7](https://cloud.githubusercontent.com/assets/1197905/26531017/700a9f20-43e9-11e7-9c8c-e368dcab968d.jpeg)
![fullsizeoutput_7f8](https://cloud.githubusercontent.com/assets/1197905/26531020/833a39b6-43e9-11e7-8aae-16198cf99420.jpeg)
![fullsizeoutput_7f9](https://cloud.githubusercontent.com/assets/1197905/26531022/93ab8336-43e9-11e7-8dc1-16853dc79944.jpeg)
![fullsizeoutput_7f6](https://cloud.githubusercontent.com/assets/1197905/26531018/765bee74-43e9-11e7-8a65-d223084805b0.jpeg)
![fullsizeoutput_7fa](https://cloud.githubusercontent.com/assets/1197905/26531031/a0eb3dfc-43e9-11e7-87c5-a7530f16c884.jpeg)
![fullsizeoutput_7f4](https://cloud.githubusercontent.com/assets/1197905/26531034/a5c36f8e-43e9-11e7-9070-110ae8d60e82.jpeg)
![fullsizeoutput_7f5](https://cloud.githubusercontent.com/assets/1197905/26531037/ac991804-43e9-11e7-9305-06349fb835df.jpeg)

**Comment by tpetricek** [comment]
I completely agree that Fable needs a logo - I think we should get multiple suggestions, so that we have a wide range of ideas to choose from! 

Here is one idea from me - this is a lot simpler, so it should work for icons and not just for the main page. It uses the HTML5 shield with current Fable.io colours. You can also combine it with other logos, though I think it needs a bit more work (the Elmish logo below is not super nice, but shows the idea).

<img src="https://cloud.githubusercontent.com/assets/485413/26531554/6a735fb2-43e3-11e7-9f39-fda3649bd361.png" width="200" />

<img src="https://cloud.githubusercontent.com/assets/485413/26531557/6f9090fa-43e3-11e7-8023-45f0ef85ba35.png" width="200" />

**Comment by evelinag** [comment]
To add some more options - I was thinking about something original that wouldn't be based on existing logos in the Javascript ecosystem. Instead I started with the name "Fable" which evokes all sorts of mythical creatures. So here's my rough initial sketch of a dragon as a logo. If you have any feedback, please let me know and I will re-draw it properly.

![fable](https://cloud.githubusercontent.com/assets/5541162/26532214/8ae6a952-43f2-11e7-8b61-9e641093c02f.png)

**Comment by ncave** [comment]
@evelinag I know it's a dragon, but all I see is [this](https://en.wikipedia.org/wiki/Hammer_and_sickle) :)
Jk of course, I hope people like it.

**Comment by evelinag** [comment]
@ncave Haha, well, that was one of the most successful logo designs of the 20th century :)

**Comment by tpetricek** [comment]
I fixed both problems with dragon! +💯 for dragons!

![dragon](https://cloud.githubusercontent.com/assets/485413/26532349/36d210be-43f6-11e7-8aa4-9ae1b7abbb0c.PNG)

**Comment by vilinski** [comment]
@evelinag remembered me rather on [Rx Logo](http://reactivex.io/assets/Rx_Logo_S.png) first. But now can't unsee that from @ncave  :))

**Comment by ncave** [comment]
@tpetricek It still doesn't [bite its tail](https://en.wikipedia.org/wiki/Ouroboros), but it's getting there.

**Comment by lucasmreis** [comment]
+1 for a logo not related to Babel or HTML. If it's already being used for things like React Native and Node, it means that Fable has the potential to be bigger than that 😄

**Comment by Pauan** [comment]
Is there some way to make the dragon in the shape of an F?

**Comment by jorgef** [comment]
I like it!

What about making the "A" look more like a "#"?

Here you have a drawing as inspiration:

![img_4689](https://cloud.githubusercontent.com/assets/941277/26537989/7501832c-4411-11e7-932f-749474a125a3.jpg)

**Comment by alfonsogarciacaro** [comment]
All of these are awesome ideas! Thanks a lot @sergey-tihon for submitting the original proposal. Actually, I like it very much and I think it's good Fable logo makes a homage to Babel the same way as the name does. (BTW, Babel is always used even when compiling for React Native or Node, as Fable itself doesn't output JS code directly.) But I'm also OK with the idea of the dragon if people like it more 🐲

**Comment by MangelMaxime** [comment]
Perhaps we could combine the proposition of @sergey-tihon with the dragon idea :)
Like replacing the symbol on the left with a dragon :) (like that everyone is happy)

**Comment by whitetigle** [comment]
The first thing I thought when looking at @sergey-tihon's logo was; 

> Woot! Fatal Fury! 

![ff_logo](https://cloud.githubusercontent.com/assets/883207/26541046/601f398e-4454-11e7-8104-4d3111d7d162.jpg)

So add dragons and Fable will sure beat'em all ;) 

As a very personal side note I'm not fan of the colors though, I prefer when there is more saturation when colors are warm.

**Comment by Zaid-Ajaj** [comment]
@sergey-tihon Fable text and colors  + the dragons from @evelinag to the left!

**Comment by vilinski** [comment]
With diamond
![fa300x300](https://cloud.githubusercontent.com/assets/259479/26544847/b7f04284-4463-11e7-8ba6-1b235fec65b0.jpg)
with f-dragon 
![f-dragon](https://cloud.githubusercontent.com/assets/259479/26544891/eb96782e-4463-11e7-878b-ac146d4e5717.jpg)

**Comment by mizzle-mo** [comment]
I like the diamond one it is my favorite so far.  Not a fan of using Babels' type style, as it is just an implementation detail.  Although they look amazing, very nice work!  

The hard part of the compiler is compiling the .fs -> .js AST.  Tying it that hard to Babel makes it even harder to swap it out for something else in the future.  I also like the dragon logos.

**Comment by mizzle-mo** [comment]
Also the first one from @tpetricek is awesome too and I think captures the essence of Fable.

**Comment by whitetigle** [comment]
Thought about something this morning from given contributions and comments. So here is the starting mockup:
![mockup](https://cloud.githubusercontent.com/assets/883207/26570595/b1d717f2-4511-11e7-8167-6f9e4146304f.png)

And here is one result: 
![fable](https://cloud.githubusercontent.com/assets/883207/26570622/d75a0106-4511-11e7-928b-866ef89cf4ff.png)

featuring:

- the beautiful dragon from @vilinski that symbolises Fable and emerges from Fsharp land to javascript realm (color transformations)
- tower of **babel**
- diamond at its core/center
- we can then add icons for fable related projectslike @sergey-tihon proposed on each roof

I did it fast, so I can refine the mockup as needed (and of course make better proportions).

**I have svg files for both the diamond and the dragon if you want to play with them!** 😄

**Comment by Pauan** [comment]
And now the bikeshedding tournament begins! :stuck_out_tongue:

**Comment by whitetigle** [comment]
@Pauan that's the limits of my english: what does it mean? 😄

**Comment by Pauan** [comment]
@whitetigle [Here is a definition for "bikeshedding"](https://en.wiktionary.org/wiki/bikeshedding), and [here is another definition](http://catb.org/jargon/html/B/bikeshedding.html). And [here is some of the history behind the term](https://en.wikipedia.org/wiki/Law_of_triviality).

It basically means people spending a lot of time arguing over "what color the bike shed should be", even though it's a minor unimportant detail.

In this case, it means "arguing over what logo Fable should have".

A tournament means that many people compete to decide who the strongest person is.There is only one winner.

So a bikeshedding tournament is a competition to decide the "best" color for the shed (or in this case, the "best" Fable logo).

Of course I have no problem with bikeshedding, my comment was just for the sake of humor.

**Comment by whitetigle** [comment]
@Pauan thanks for the explanation! I feel smarter now 😄

**Comment by tpetricek** [comment]
With the flourishing of ideas on this thread, allow me to share the only design advice that I know (because a colleague told this to me once a long time ago): 

> A good logo is one that you could recognise if someone draw it in a sand with a stick.

Of course, there are good counter examples to this, but I think it is something worth keeping in mind even in the modern digital age. It also means that the logo will work in black & white and you will be able to resize it to 16x16 pixels for favicon.

I think many ideas here have quite elaborate story behind them, which is certainly fun, but they would not be usable as logos in the above sense of a logo. There is nothing wrong with that - it could still be an illustration for the fable web page - but I think if we want a logo, it is worth striving for simplicity (also because simplicity means it can be done without very good artistic skills :-))

**Comment by voronoipotato** [comment]
what about a ƒ shaped dragon, this has a nice dual meaning because the ƒ highlights the functional nature of fable.

**Comment by voronoipotato** [comment]
Also I think referring design decisions as bikeshedding really undermines the importance of the decision. Bikeshedding is strictly relegated to decisions of low importance, whereas the logo is of critical importance. Also there is merely an illusion that it takes little skill to make a good logo, when actually it takes a good amount of effort to actually fashion a quality logo. It might even be valuable to pool together some money to pay someone to make a professional logo.

**Comment by Krzysztof-Cieslak** [comment]
Small reminder - using F# logo in original colors in context "which could imply representation of the F# Software Foundation directly" is not legal. 

That's FSSF Contribution to our OSS ecosystem, we can't even use logo :)

**Comment by lucasmreis** [comment]
Just adding some inspiration sources:

I like the idea of a dragon because of what "fable" means. When I think of a fable, I usually think of Aesop's fables ( https://en.wikipedia.org/wiki/Aesop%27s_Fables ), mainly the Tortoise and The Hare ( https://en.wikipedia.org/wiki/The_Tortoise_and_the_Hare ).

Also, + 1 for a logo that is recognizable even as a favicon :)

**Comment by Zaid-Ajaj** [comment]
@sergey-tihon Can I use one of your logo's in an article of mine? :smile:

**Comment by psb** [comment]
Spanish inspired "fa-bull" :

1. Plain
![fable-spanish-bg-wab](https://cloud.githubusercontent.com/assets/2823149/26606141/b05c7260-4588-11e7-96a7-c5b58cdf469f.png)

2.
![fable-spanish-bg-baw](https://cloud.githubusercontent.com/assets/2823149/26606155/c02b81d6-4588-11e7-8f59-4ecffa4f5f69.png)

3. 
![fable-spanish-bg](https://cloud.githubusercontent.com/assets/2823149/26606173/cf27f246-4588-11e7-9de1-0138639efb3b.png)

4. Plain with framework name (framework font is [Rajdhani](http://foundation.fsharp.org/logo))
![fable-spanish-plus-framework](https://cloud.githubusercontent.com/assets/2823149/26606192/e1357cce-4588-11e7-8882-91771150415d.png)

5. With Spanish flag colours (created by accident!)
![fable-spanish-bg-accidental-yellow](https://cloud.githubusercontent.com/assets/2823149/26606294/49fae974-4589-11e7-91f1-9ecfaf7c7594.png)

6. Spanish flag colours and framework name (in white)
![fable-spanish-plus-framework-accidental](https://cloud.githubusercontent.com/assets/2823149/26606344/79e29c68-4589-11e7-9f06-2f1fe2bf3d75.png)

7. Plain favicon
![fable-spanish-bull-fav](https://cloud.githubusercontent.com/assets/2823149/26606399/a88bcdb4-4589-11e7-9d89-77e27739c5aa.png)

8. Spanish flag colours favicon
![fable-spanish-bull-fav-acc](https://cloud.githubusercontent.com/assets/2823149/26606420/b8b48622-4589-11e7-9c47-a6e7d3dba333.png)

That's what I've mustered fumbling around with Inkscape. Nothing deep and meaningful; just a play on the word 'fable' and a nod to Spain.

**Comment by tpetricek** [comment]
@psb I like the colour scheme and the simple line/area cubistic style! Numbers 5 and 8 are my favourites. I wonder if just "F-bull" could be a good mix of 5 and 8? (in any case, this is really nice work!)

**Comment by Pauan** [comment]
@psb I really like the combination of F and |>

Not liking the bull part as much, but it's a neat pun.

**Comment by sergey-tihon** [comment]
@Zaid-Ajaj yes, sure

**Comment by psb** [comment]
The files are [here](https://github.com/psb/Fable-Compiler-Logos). I could do some minor changes, but my Inkscape and artistic skills are probably maxing out for me to make improvements. The files are there for anybody to use, improve and professionalise, if they wish to do so.

**Comment by whitetigle** [comment]
Hi there, another idea that popped in my mind tonight. 😆 

![big logo](https://cloud.githubusercontent.com/assets/883207/26653988/572622a4-4655-11e7-85d3-9f8183cb60fe.png)

misc ideas: |>,  JS yellow, fsharp blue (is there an official color?), tunnel /  babel tower, fsharp is the core, of the JS structure aiming towards the infinite and beyond (tm)

Drawing feels so good for the mind after coding 🌈 

@psb I really like the bull favicon: simple, warm, clear 👍

**Comment by sergey-tihon** [comment]
One more option from our side (with dragon)
![logofablenew-02](https://cloud.githubusercontent.com/assets/1197905/26680118/be8291ea-46e0-11e7-837e-763804e91b88.png)
![logofablenew-01](https://cloud.githubusercontent.com/assets/1197905/26680122/c37e4716-46e0-11e7-8295-267629caa98f.png)
<img width="400" alt="screen shot 2017-06-01 at 15 41 11" src="https://cloud.githubusercontent.com/assets/1197905/26680163/ee34c2a0-46e0-11e7-9fbc-8f4dc736dd95.png">
<img width="576" alt="screen shot 2017-06-01 at 15 46 21" src="https://cloud.githubusercontent.com/assets/1197905/26680301/97010920-46e1-11e7-974d-271d4e8675da.png">

**Comment by et1975** [comment]
I like the dragon, but I thought I'd throw a different idea out, 
Japanese for fable is `寓話`, here's something one could draw in the sand (I think it means "tale"):
Simple: 
![tale](https://cloud.githubusercontent.com/assets/623703/26681892/9f950c24-46ac-11e7-8b9c-6c844109e2e9.png)
Spanish edition:
![tale_red](https://cloud.githubusercontent.com/assets/623703/26682297/00c1a128-46ae-11e7-9259-a5e6fa62bafb.png)

**Comment by MangelMaxime** [comment]
@sergey-tihon I really like this new design.
More simple, and we could add the library logo in the dragon body :)

**Comment by whitetigle** [comment]
@et1975 I love kanjis and I like your simple rounded design. This is what I love with korean / japanese characters. They catch the eye immediately and can be re-designed according to the needs.

@sergey-tihon I really like the 3rd design! (simpler, no outline)

**Comment by Krzysztof-Cieslak** [comment]
I really like cubistic design proposed by @psb. Maybe variation of 5 with full FABLE instead of FA-bull_symbol ?

**Comment by ncave** [comment]
@sergey-tihon The blue ones are really nice, with or without outline, perhaps with an eye and a bit more natural body posture in the middle, something like that:
- Looking a vaguely a bit to the left:
![image](https://cloud.githubusercontent.com/assets/777696/26685838/126f914a-46a0-11e7-9fe0-9322eef0c433.png)
- Looking forward:
![image](https://cloud.githubusercontent.com/assets/777696/26686043/ae66bcea-46a0-11e7-9759-25c48da4a1a1.png)

**Comment by Worldbeater** [comment]
In my humble opinion here is the best logo for Fable:
![image](https://cloud.githubusercontent.com/assets/6759207/26695367/4a232b9c-4713-11e7-9f31-fb8f953fa07c.png)
Simple, flat and modern. It's great, my heart now belongs to it!

**Comment by alfonsogarciacaro** [comment]
All are great ideas, thanks a lot everybody for your proposals! :clap: :clap:

But I've also fallen in love with the dragon, awesome work @sergey-tihon! 🔥 🐉 🔥 Maybe the dragon can replace the F in Fable?

<img width="239" alt="screen shot 2017-06-02 at 10 02 48 am" src="https://cloud.githubusercontent.com/assets/8275461/26716759/165fcdac-477b-11e7-87d5-226f6cdc59bd.png">

**Comment by Pauan** [comment]
@alfonsogarciacaro :+1: :shipit: :clap: :dancer: :shipit:

Personally, I think the dragon is a bit too tall, if it was shrunk down to 50-75% of its current size it'd be perfect.

**Comment by psb** [comment]
Well, for completeness I did some all text logos:

A: small 'e'
![fable-compiler-logo-plain-all-text-no-bull-a](https://cloud.githubusercontent.com/assets/2823149/26722301/38c5be18-4787-11e7-9c2d-9858499c4742.png)

B: big 'e'
![fable-compiler-logo-plain-all-text-no-bull-b](https://cloud.githubusercontent.com/assets/2823149/26722091/749bb2a4-4786-11e7-8867-fe47ab8bccb0.png)

C: medium 'e'
![fable-compiler-logo-plain-all-text-no-bull-c](https://cloud.githubusercontent.com/assets/2823149/26722112/812b727a-4786-11e7-860b-3debf3967768.png)

Favicon:
![fable-compiler-logo-plain-all-text-no-bull-favicon](https://cloud.githubusercontent.com/assets/2823149/26722170/b7757128-4786-11e7-81bc-fe1319f0b304.png)

And, using my best marketing spiel, they can be customised to meet all your logo needs:
![fable-compiler-logo-plain-all-text-no-bull-c-conf](https://cloud.githubusercontent.com/assets/2823149/26722204/dbecc9de-4786-11e7-8801-1ec1ffb1107b.png)
![fable-compiler-logo-plain-all-text-no-bull-c-elm](https://cloud.githubusercontent.com/assets/2823149/26722206/dbf2bf4c-4786-11e7-840a-311103e917ed.png)
![fable-compiler-logo-plain-all-text-no-bull-c-react](https://cloud.githubusercontent.com/assets/2823149/26722205/dbf1fddc-4786-11e7-9ea3-3a24b42d0dca.png)

**Comment by alfonsogarciacaro** [comment]
@psb I liked the coloured versions! Looks like a Picasso-Miró fusion ;)

**Comment by Zaid-Ajaj** [comment]
How can we even decide here, they are all beautiful and awesome :heart: :clap: :clap: :clap:

**Comment by MangelMaxime** [comment]
I have a hard time reading the logos from @psb 
Not saying they are bad but I need to concentrate at first to read the Fable word.

Other than that the colored version are really cool

**Comment by Pauan** [comment]
@Zaid-Ajaj As I said: bikeshedding tournament. :stuck_out_tongue:

**Comment by sergey-tihon** [comment]
Probably the final option from our side...

Smaller dragon that replace F in Fable word
<img width="400" alt="screen shot 2017-06-02 at 15 28 30" src="https://cloud.githubusercontent.com/assets/1197905/26725706/7e2db778-47a8-11e7-8603-2ba82ac49f24.png">

and here is how logo can be branded
<img width="400" alt="screen shot 2017-06-02 at 15 33 49" src="https://cloud.githubusercontent.com/assets/1197905/26725828/071d8180-47a9-11e7-948c-a2d6a97a25f1.png">
<img width="400" alt="screen shot 2017-06-02 at 15 30 51" src="https://cloud.githubusercontent.com/assets/1197905/26725763/bba7cfda-47a8-11e7-8b90-e259ce8a564f.png">

**Comment by MangelMaxime** [comment]
You got my vote @sergey-tihon 
I really like the logo. It's clean and the colors are really cool

**Comment by Pauan** [comment]
I also vote for the final logo of @sergey-tihon. We'll need a favicon size logo as well, I think.

**Comment by MangelMaxime** [comment]
Perhaps the fav icon can be the "dragon" ?

**Comment by Pauan** [comment]
Yes, that's what I was thinking, just resized into a small square/circle.

**Comment by Worldbeater** [comment]
A dragon on transparent layout would be the best option for a small logo for github/fav, I think. Great work, @sergey-tihon!

**Comment by sergey-tihon** [comment]
Favicon for site:
[favicon_01_Tsx_icon.ico.zip](https://github.com/fable-compiler/Fable/files/1069055/favicon_01_Tsx_icon.ico.zip)

Square for github/twitter organization (Header background in twitter can be yellow):
![github-01](https://user-images.githubusercontent.com/1197905/27047757-e099870a-4fb1-11e7-8b46-8734c5870e56.png)
<img width="1024" alt="screen shot 2017-06-12 at 21 06 44 copy" src="https://user-images.githubusercontent.com/1197905/27048217-a5148692-4fb3-11e7-9a3f-0403c810e3eb.png">

Large transparent option for prints
![transparentfable-01](https://user-images.githubusercontent.com/1197905/27047311-56453e74-4fb0-11e7-905c-0a05e5fd87ca.png)

**Comment by realvictorprm** [comment]
This is awesome :smile:

**Comment by alfonsogarciacaro** [comment]
@psb Do you mind if we use your logo for FableConf?

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Why not the ones from @sergey-tihon ? Wasn't this one we choose ?

**Comment by alfonsogarciacaro** [comment]
Sergey's logo is the one for Fable, yes, the [Twitter account](https://twitter.com/FableCompiler) already uses it 😄 I was just thinking it'd be nice to use @psb proposal for [FableConf](https://www.eventbrite.es/e/fableconf-bordeaux-tickets-34089709238), it just fits so well with the French colors :wink:

![dbecc9de-4786-11e7-8801-1ec1ffb1107b](https://user-images.githubusercontent.com/8275461/27159554-2924c5a8-516e-11e7-885f-729d968ec3ef.png)

**Comment by MangelMaxime** [comment]
Hum ah yes 😊

**Comment by whitetigle** [comment]
Hi there! 
I would like to propose a little bit more saturated/punchy color palette 😄 

![antes_despues](https://user-images.githubusercontent.com/883207/27172558-f7908e4e-51b5-11e7-8767-317421d219c3.jpg)

![fable_logo_newblue](https://user-images.githubusercontent.com/883207/27172568-03dda86c-51b6-11e7-9f41-db20246c9d30.png)

**Comment by psb** [comment]
@alfonsogarciacaro Sure. All the files are [here](https://github.com/psb/Fable-Compiler-Logos). The blue and red in the logo are the official colours used in the French flag, but it's easy to change them if you need to do so.

**Comment by MangelMaxime** [comment]
To be honest I prefer the actual blue :) Than the punchy one.

**Comment by Pauan** [comment]
@MangelMaxime I think having them side by side makes the saturated version look bad. Try covering up the left side with your hand, then the right side looks a lot better.

**Comment by alfonsogarciacaro** [comment]
Nice trick @Pauan! The saturated version actually looks better, specially for Twitter, I'll use it! Thanks @whitetigle!

**Comment by MangelMaxime** [comment]
Just if need here is the logo used for the Github repo with only the symbol :)

![fable_logo_github](https://user-images.githubusercontent.com/4760796/27398470-1df9027e-56ba-11e7-9183-8a0a0be07484.png)

**Comment by psb** [comment]
There is a trimmed and optimised svg version of the fable conf logo [here](https://github.com/psb/Fable-Compiler-Logos/blob/master/fable-compiler-logo-plain-all-text-no-bull-C-conf-optimised.svg). It's smaller than the png and should look better (i.e. not blurry) at all sizes.

**Comment by alfonsogarciacaro** [comment]
Thanks @psb, I was about to ask you that ;) I'm happy yo saw the web with the log, it looks very nice :clap:

**Comment by psb** [comment]
De nada.

**Comment by sergey-tihon** [comment]
The SVG version
[fablelogo_copy.svg.zip](https://github.com/fable-compiler/Fable/files/1149505/fablelogo_copy.svg.zip)
